In [2]:
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as lg

In [16]:
nx = 8
ny = 5
dx = 1.0
dy = 1.0
dx_2 = 1.0 / (dx * dx)
dy_2 = 1.0 / (dy * dy)


def BuildLAPD():
    """
    Laplacian with Dirichlet BC

    """
    # Dropping ghost points (-2)
    NXi = nx
    NYi = ny

    # 1D Laplace operator

    # X-axis
    # Diagonal terms
    dataNXi = [np.ones(NXi), -2 * np.ones(NXi), np.ones(NXi)]

    # Boundary conditions
    dataNXi[1][0] = -3.  # Dirichlet
    dataNXi[1][-1] = -3.  # Dirichlet

    # Y-axis
    # Diagonal terms
    dataNYi = [np.ones(NYi), -2 * np.ones(NYi), np.ones(NYi)]

    # Boundary conditions
    dataNYi[1][0] = -3.  # Dirichlet
    dataNYi[1][-1] = -3.  # Dirichlet

    # Their positions
    offsets = np.array([-1, 0, 1])
    DXX = sp.dia_matrix((dataNXi, offsets), shape=(NXi, NXi)) * dx_2
    DYY = sp.dia_matrix((dataNYi, offsets), shape=(NYi, NYi)) * dy_2
    # print(DXX.todense())
    # print(DYY.todense())

    # 2D Laplace operator
    LAPD = sp.kron(sp.eye(NYi, NYi), DXX) + sp.kron(DYY, sp.eye(NXi, NXi))

    return LAPD


def BuildLAPN():
    """
    Laplacian matrix for Phi with Neumann BC

    The value is set at one point (here [0][1]) to ensure uniqueness

    """
    # Dropping ghost points (-2)
    NXi = nx
    NYi = ny

    # 1D Laplace operator

    # X-axis
    # Diagonal terms
    dataNXi = [np.ones(NXi), -2 * np.ones(NXi), np.ones(NXi)]

    # Boundary conditions
    dataNXi[1][0] = -1.  # Neumann
    dataNXi[1][-1] = -1.  # Neumann

    # Y-axis
    # Diagonal terms
    dataNYi = [np.ones(NYi), -2 * np.ones(NYi), np.ones(NYi)]

    # Boundary conditions
    dataNYi[1][0] = -1.  # Neumann
    dataNYi[1][-1] = -1.  # Neumann

    # Their positions
    offsets = np.array([-1, 0, 1])
    DXX = sp.dia_matrix((dataNXi, offsets), shape=(NXi, NXi)) * dx_2
    DYY = sp.dia_matrix((dataNYi, offsets), shape=(NYi, NYi)) * dy_2
    # print(DXX.todense())
    # print(DYY.todense())

    # 2D Laplace operator
    LAP = sp.kron(DXX, sp.eye(NYi, NYi)) + sp.kron(sp.eye(NXi, NXi), DYY)

    # BUILD CORRECTION MATRIX

    # Upper Diagonal terms
    # dataNYNXi = [np.zeros(NYi * NXi)]
    # offset = np.array([1])

    # # Fix coef: 2+(-1) = 1 ==> Dirichlet at a single point
    # dataNYNXi[0][1] = -1 * dx_2

    # LAP0 = sp.dia_matrix((dataNYNXi, offset), shape=(NYi * NXi, NYi * NXi))

    # tmp = LAP + LAP0
    # print(LAP.todense())
    # print(LAP0.todense())
    # print(tmp.todense())

    return LAP

In [17]:
LD = BuildLAPD()
LN = BuildLAPN()

In [18]:
# change num of horizontal lines to be printed
np.set_printoptions(threshold=np.inf, linewidth=800)
print(LD.todense())

[[-6.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -5.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -5.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -5.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -5.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -5.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 

In [19]:
print(LN.todense())

[[-1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 

In [4]:
np.linspace(0.1, 1.0, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [5]:
Lx = 2.0
Ly = 1.0
nx = 8
ny = 5
dx = Lx / nx
dy = Ly / ny


X = np.linspace(dx/2, Lx - dx/2, nx)
Y = np.linspace(dy/2, Ly - dy/2, ny)
X, Y = np.meshgrid(X, Y, indexing='ij')

In [6]:
X

array([[0.125, 0.125, 0.125, 0.125, 0.125],
       [0.375, 0.375, 0.375, 0.375, 0.375],
       [0.625, 0.625, 0.625, 0.625, 0.625],
       [0.875, 0.875, 0.875, 0.875, 0.875],
       [1.125, 1.125, 1.125, 1.125, 1.125],
       [1.375, 1.375, 1.375, 1.375, 1.375],
       [1.625, 1.625, 1.625, 1.625, 1.625],
       [1.875, 1.875, 1.875, 1.875, 1.875]])

In [7]:
Y

array([[0.1, 0.3, 0.5, 0.7, 0.9],
       [0.1, 0.3, 0.5, 0.7, 0.9],
       [0.1, 0.3, 0.5, 0.7, 0.9],
       [0.1, 0.3, 0.5, 0.7, 0.9],
       [0.1, 0.3, 0.5, 0.7, 0.9],
       [0.1, 0.3, 0.5, 0.7, 0.9],
       [0.1, 0.3, 0.5, 0.7, 0.9],
       [0.1, 0.3, 0.5, 0.7, 0.9]])

In [9]:
X[0,2]

0.125